export interface Colors{
    blue:string,
    background_blue: string,
    background_black: string,
    card: string,
    dark_sky_blue:string,
    indigo:string,
    purple:string
    pink:string,
    red:string,
    orange:string,
    yellow:string,
    yellow_white: string,
    green:string,
    light_green: string,
    light_red: string,
    teal:string,
    cyan:string,
    white:string,  
    whiteGray: string, 
    gray:string,   
    gray_dark:string,   
    primary:string,
    secondary:string,
    success:string,
    info:string,
    warning:string,
    danger:string,
    disable: string,
    light:string,
    dark:string,   
    gray_white: string,
    gray_100:string,
    gray_200:string,   
    gray_300:string,
    gray_400:string,
    gray_500:string,   
    gray_600:string,   
    gray_700:string,   
    gray_800:string,   
    gray_900:string,   
    coral_100:string,
    coral_400:string,
    coral_500:string,
    coral_600:string,
    coral_800:string,
    primary_100:string,
    primary_200:string,
    primary_300:string,
    primary_400:string,
    teal_100:string,
    teal_400:string,
    teal_700:string,
    teal_800:string,
    teal_900:string,
    davy_gray:string,   
    medium:string,
    breakpoint_xs:string,
    breakpoint_sm:string,    
    breakpoint_md:string,
    breakpoint_lg:string
}